In [7]:
import numpy as np
from sympy.utilities.iterables import multiset_permutations

In [11]:
nInvestors = 7
table = np.arange(nInvestors)

In [15]:
investors = table.copy()

for investorCombination in multiset_permutations(investors):
    print(investorCombination)
    nHappyInvestorArray = np.zeros(nInvestors)
    for iShift in range(nInvestors):
        nHappyInvestorArray[iShift] = np.count_nonzero(table == investorCombination)
        if nHappyInvestorArray[iShift] > 1:
            break
        investorCombination = np.roll(investorCombination, shift=1)
    print(nHappyInvestorArray)
    if np.count_nonzero(nHappyInvestorArray > 1) == 0:
        print("Solution!!:")
        print(investorCombination+1)
        break
    

[0, 1, 2, 3, 4, 5, 6]
[7. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 3, 4, 6, 5]
[5. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 3, 5, 4, 6]
[5. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 3, 5, 6, 4]
[4. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 3, 6, 4, 5]
[4. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 3, 6, 5, 4]
[5. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 4, 3, 5, 6]
[5. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 4, 3, 6, 5]
[3. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 4, 5, 3, 6]
[4. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 4, 5, 6, 3]
[3. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 4, 6, 3, 5]
[3. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 4, 6, 5, 3]
[4. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 5, 3, 4, 6]
[4. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 5, 3, 6, 4]
[3. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 5, 4, 3, 6]
[5. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 5, 4, 6, 3]
[4. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 5, 6, 3, 4]
[3. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 5, 6, 4, 3]
[3. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 6, 3, 4, 5]
[3. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 6, 3, 5, 4]
[4. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 6, 4, 3, 5]
[4. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 6, 4, 5, 3]
[5. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 